import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    auth
}: Readonly<{
    children: React.ReactNode,
    auth: React.ReactNode
}>) {
    return (
        <div className="p-2 bg-amber-900">
            <h1 className="text-2xl font-bold">(Marketing) Layout</h1>
            <nav className="bg-red-400 p-4 rounded-md">
                <ul className="flex items-center gap-2">
                    <li>
                        <Link href={'/'}>Home</Link>
                    </li>
                    <li>
                        <Link href={'/blog'}>Blog</Link>
                    </li>
                    <li>
                        <Link href={'/login'}>Login</Link>
                    </li>
                </ul>
            </nav>
            {children}
            {auth}
        </div>
    );
}
